package ai.agentic.fs;

public class PomTemplate {

    public static String render(
            String groupId,
            String artifactId,
            String version,
            int javaVersion,
            String bootVersion,
            boolean web,
            boolean jpa,
            boolean validation,
            DatabaseType database,
            boolean swaggerEnabled
    ) {

        validateConfiguration(jpa, database);

        StringBuilder deps = new StringBuilder();

        // Web
        if (web) {
            deps.append("""
                    <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-web</artifactId>
                    </dependency>
                    """);
        }

        // JPA
        if (jpa) {
            deps.append("""
                    <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-data-jpa</artifactId>
                    </dependency>
                    """);
        }

        // Validation
        if (validation) {
            deps.append("""
                    <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-validation</artifactId>
                    </dependency>
                    """);
        }

        // Database Driver
        switch (database) {
            case MYSQL -> deps.append("""
                    <dependency>
                        <groupId>com.mysql</groupId>
                        <artifactId>mysql-connector-j</artifactId>
                        <scope>runtime</scope>
                    </dependency>
                    """);

            case POSTGRES -> deps.append("""
                    <dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <scope>runtime</scope>
                    </dependency>
                    """);

            case H2 -> deps.append("""
                    <dependency>
                        <groupId>com.h2database</groupId>
                        <artifactId>h2</artifactId>
                        <scope>runtime</scope>
                    </dependency>
                    """);

            case NONE -> {
                // no driver
            }
        }

        // Swagger
        if (swaggerEnabled) {
            deps.append("""
                    <dependency>
                        <groupId>org.springdoc</groupId>
                        <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                        <version>2.5.0</version>
                    </dependency>
                    """);
        }

        // Lombok (optional but safe)
        deps.append("""
                <dependency>
                    <groupId>org.projectlombok</groupId>
                    <artifactId>lombok</artifactId>
                    <version>1.18.32</version>
                    <scope>provided</scope>
                </dependency>
                """);

        return """
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                         http://maven.apache.org/xsd/maven-4.0.0.xsd">

                  <modelVersion>4.0.0</modelVersion>

                  <parent>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-parent</artifactId>
                    <version>%s</version>
                    <relativePath/>
                  </parent>

                  <groupId>%s</groupId>
                  <artifactId>%s</artifactId>
                  <version>%s</version>
                  <packaging>jar</packaging>
                  <name>%s</name>
                  <description>Generated by Gosi Brain</description>

                  <properties>
                    <java.version>%d</java.version>
                  </properties>

                  <dependencies>
                %s
                  </dependencies>

                  <build>
                    <plugins>

                      <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                      </plugin>

                      <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>3.11.0</version>
                        <configuration>
                          <source>${java.version}</source>
                          <target>${java.version}</target>
                          <annotationProcessorPaths>
                            <path>
                              <groupId>org.projectlombok</groupId>
                              <artifactId>lombok</artifactId>
                              <version>1.18.32</version>
                            </path>
                          </annotationProcessorPaths>
                        </configuration>
                      </plugin>

                    </plugins>
                  </build>

                </project>
                """.formatted(
                bootVersion,
                groupId,
                artifactId,
                version,
                artifactId,
                javaVersion,
                deps.toString()
        );
    }

    private static void validateConfiguration(boolean jpa, DatabaseType database) {
        if (jpa && database == DatabaseType.NONE) {
            throw new IllegalStateException(
                    "Invalid configuration: JPA requires a database."
            );
        }

        if (!jpa && database != DatabaseType.NONE) {
            throw new IllegalStateException(
                    "Invalid configuration: Database selected but JPA disabled."
            );
        }
    }
}
